[tool.black]
line-length = 120

exclude = '''
(
  /(
      \.git
    | venv
    | \.venv
    | requirements\/\*
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 120

skip = '.venv, venv'
src_paths = ["TestTask"]
force_grid_wrap = 0
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true
